// Auto-generated by Poink-and-Clink exporter for Aseprite.
// DO NOT MODIFY - your changes will be overwritten when exporting!

VAR C_exterior_bg = "0,0,96,64"
VAR C_woodpile = "57,42,69,48"
VAR C_smoke = "76,0,86,8"
VAR C_trees = "0,1,56,48"
VAR C_cabin = "70,9,96,48"
VAR C_interior_bg = "0,0,96,64"
VAR C_fire = "77,30,95,45"
VAR C_door = "2,9,27,48"
VAR C_window = "31,9,61,32"