-- TODO: make it work as both a standalone script and a module.
--[[
Export images and slice coordinate data for Poink-and-Clink game template.

All exported data will be placed in a directory named "aseprite-export" alongside the aseprite file being exported, according to the following directory structure:

filename.aseprite
aseprite-export/
    images/
        filename.layer1.tag1.gif
        filename.layer1.tag2.gif
        ... etc.
    ink/
        filename.ink

IMAGE DATA NOTES:

The tag named "default" will be omitted from the generated filename
    (i.e. filename.layer1.gif will be the "default" animation of layer1).
Layer groups will be exported collectively as a single layer.
Try not to include spaces in layer or tag names.

SLICE DATA NOTES:

A slice named "example" spanning from 0,0 to 10,10 with metadata "hovertext" will be exported in ink as:

VAR C_example = "0,0,10,10 hovertext"

]]--

--local sprite = app.activeSprite
local sprite = nil

-- hide all listed layers, including children recursively
local function hideAllLayers(layers)
  for index, layer in ipairs(layers) do
    layer.isVisible = false
    if layer.isGroup then
        hideAllLayers(layer.layers)
    end
  end
end

-- show listed layer, including children recursively, and any parents
local function showLayer(layer, recursive)
    layer.isVisible = true
    if layer.isGroup and recursive then
        for i, l in ipairs(layer.layers) do
            print("showing layer " .. layer.name)
            showLayer(l,true)
        end
    end
    if layer.parent ~= sprite then
        -- Note: don't call recursively on parent!!
        showLayer(layer.parent,false)
    end
end


-- export a gif of the given layer and tag
local function exportLayerTag(image_dir, layer, tag)
    local filename = layer.name .. "." .. tag.name .. ".gif"
    if tag.name == "default" then
        -- omit "tag" part of filename
        filename = layer.name .. ".gif"
    end
    local full_path = app.fs.joinPath(image_dir, filename)
    
    -- Note: transaction/undo didn't seem to work for layer visibility,
    ---  I guess because changing layer visibility is not a "command"?
    --local prev_visibility = hideAllLayers(sprite.layers)
    --layer.isVisible = true
    hideAllLayers(sprite.layers)
    showLayer(layer,true)
    app.command.SaveFileCopyAs{
        ui=false,
        filename=full_path,
        tag=tag.name,
    }
    --resetVisibility(sprite.layers, prev_visibility)
end

-- TODO Bounding boxes from layers, not slices
local function exportInkData(filename, scene_title)
    local ink_content = [[
// Auto-generated by Poink-and-Clink exporter for Aseprite.
// Do not modify this file - your changes will be overwritten when exporting!

]]
    for i, slice in ipairs(sprite.slices) do
        local s = string.format("VAR %s = \"%d,%d,%d,%d %s\"\n",
            "C_" .. slice.name:gsub(" ","_"),
            slice.bounds.x,
            slice.bounds.y,
            slice.bounds.x + slice.bounds.width,
            slice.bounds.y + slice.bounds.height,
            slice.data
        )
        ink_content = ink_content .. s
    end


    local file = io.open(filename,"w")
    if file then
        file:write(ink_content)
    else
        print("Error: unable to save file: " .. filename)
    end
    file:close()
end

-- TODO: move copy_file, copy_dir to generic "copy" script.
local function copy_file(src,dest)
    local f_in = io.open(src,"rb")
    local content = f_in:read("*all")
    f_in:close()
    local f_out = io.open(dest,"wb")
    f_out:write(content)
    f_out:close()
end

local function copy_dir(src, dest)
    app.fs.makeAllDirectories(dest)
    for _,fname in pairs(app.fs.listFiles(src)) do
        local f_src = app.fs.joinPath(src,fname)
        local f_dest = app.fs.joinPath(dest,fname)
        if app.fs.isFile(f_src) then
            copy_file(f_src,f_dest)
        elseif app.fs.isDirectory(f_src) then
            copy_dir(f_src,f_dest)
        end
    end
end

local function main(plugin)
    sprite = app.activeSprite
    -- Confirmation dialog 

    local dialog = Dialog()
    dialog:label{ id="label", text="Export poink-and-clink project?" }
    dialog:button{ id="ok", text="Export" }
    dialog:button{ id="cancel", text="Cancel", onclick = function() dialog:close() end }
    dialog:show()

    if not dialog.data.ok then
        return
    end
    
    -- directory where the export "html" directory will go
    -- (currently just the directory where .ase file is located)
    local file_dir = app.fs.filePath(sprite.filename)
   
    -- Copy the web template to destination folder
    local copy_from = app.fs.joinPath(plugin.path,"web-template")
    local export_dir = app.fs.joinPath(file_dir,"html")
    copy_dir(copy_from, export_dir)
    
    -- Export details:
    --  create "aseprite-export" dir in same directory as .aseprite file
    --  within that, create "images" and "ink"
    --  this should be the most practical setup, I think
    local scene_title = app.fs.fileTitle(sprite.filename)
    local image_dir = app.fs.joinPath(export_dir,"images")

    -- Open temporary sprite for editing
    local temp_sprite = Sprite(sprite)
    temp_sprite.filename = "(TEMP - exporting)"
    local old_sprite = sprite
    sprite = temp_sprite 
    
    -- Export images (one per tag & layer)
    for i, layer in ipairs(sprite.layers) do
        for i, tag in ipairs(sprite.tags) do
            -- Expands only top-level groups
            if layer.isGroup then
                for i, sublayer in ipairs(layer.layers) do
                    exportLayerTag(image_dir, sublayer, tag)
                end
            else
                exportLayerTag(image_dir, layer, tag)
            end
        end
    end

    -- Export ink
    -- TODO: Get bounding box from each layer, rather than slices.
    local ink_filename = app.fs.joinPath(file_dir,"EXPORT.ink")
    exportInkData(ink_filename)

    -- Close the temporary sprite
    sprite = old_sprite
    temp_sprite:close()
end

-- main()
return main
